### ISSUE TITLE
Found this in error logs

### ISSUE THREAD

**Issue by scriptzteam** [thejordanprice/p2pspider#1]
Thx for nice piece of code! .)

`root@GBiT:~/p2pspider# tail -f /root/.pm2/logs/daemon-error-1.log(node:9523) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client`

**Comment by thejordanprice** [comment]
This isn't really an ISSUE, its more of a thing complaining about 'promises' and the way it is connecting to the DB. Eventually I will correct that issue, I've just been working too much to actually fix things.

Pull requests that are decent should be accepted.

**Comment by thejordanprice** [comment]
I've patched this issue.
