### ISSUE TITLE
Occasionally disk usage is very high

### ISSUE THREAD

**Issue by xeeoon** [thejordanprice/p2pspider#2]
Hi！
![screenshot_20171120_225605](https://user-images.githubusercontent.com/24264034/33026864-76ea0680-ce4c-11e7-981e-8668e3a91e02.png)
Is this normal? When the program is running, occasionally disk io speed is very high that vps stucked a few times.
Using the default configuration.

**Comment by xeeoon** [comment]
Well, maybe I should reduce the number of daemon instances, but this disk rate is amazingly high. Can this be optimized?

**Comment by thejordanprice** [comment]
Edit the ecosystem.json file and lower the number of daemons you have running, possibly even the RAM limit. It'll help a lot. Then a 'pm2 restart all' should work.

**Comment by thejordanprice** [comment]
I will be adding redis to the stack to attempt limiting the read and writes to the disk. Hopefully that will solve the issue you are talking about. I have noticed it in the past as well. Redis will probably speed up the entire system as well in multiple ways. Mongo will still be the database though, Redis will only be controlling the magnets being re-announced constantly to keep Mongo slightly less busy.

I hope to have this added soon in the near future.

**Comment by thejordanprice** [comment]
I have added redis to the stack and would like to say that it will be much more efficient on the disk usage.
